#!/usr/bin/env ruby
#^syntax detection


role "ksclarke.ansible-samvera",
      github: "ksclarke/ansible-samvera",
      ref: "origin/test"

# more roles can be added here, you can pull them from GitHub or from Ansible Galaxy
# docs here: https://github.com/bcoe/librarian-ansible
